version: "3.9"

services:
  api:
    build: ./api/
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3000

  db:
    image: postgres:14.3
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=Trustno1

  front:
    build: ./front/
    ports:
      - 8080:80
