services:
  api:
    build: ./api/
    expose:
      - 4242
    ports:
      - 4242:4242
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=4242

  db:
    image: postgres
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=Trustno1

  front:
    image: httpd
    ports:
      - 80:8080
    volumes:
      - ./front/:/usr/local/apache2/htdocs/
