version: "3.7"

services:
  db:
    build: ./db/
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

  api:
    build: ./api/
    expose:
      - ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      RUST_BACKTRACE: 1
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: ${API_PORT}
      ROCKET_SECRET_KEY: 17tu+oEIpQy3OwTKhEDUIhr1HFWyKcb92xzPpLS3t3Y=
      ROCKET_DATABASES: >
        {${DB_USER}={
          url=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_USER}
        }}
    depends_on:
      - db

  front:
    build: ./front/
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - api
